version: 2.1

jobs:
  full_gdpr_pipeline:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Run mock app to generate logs
          command: |
            mkdir -p src/logs
            python src/app.py
      - run:
          name: Check audit logs
          command: bash src/scripts/check-audit-logs.sh
      - run:
          name: Check consent logs
          command: bash src/scripts/check-consent-logs.sh
      - run:
          name: Generate report
          command: python src/scripts/generate_report.py
      - store_artifacts:
          path: src/logs
          destination: logs

workflows:
  version: 2
  gdpr_pipeline:
    jobs:
      - full_gdpr_pipeline
