version: 2.1

jobs:
  run_mock_python_app:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Run mock app to generate logs
          command: |
            mkdir -p src/logs
            python src/app.py
      - persist_to_workspace:
          root: .
          paths:
            - src/logs

  audit_check:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Check audit logs
          command: bash src/scripts/check-audit-logs.sh

  consent_check:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Check consent logs
          command: bash src/scripts/check-consent-logs.sh

  generate_report:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Generate compliance report
          command: python src/scripts/generate_report.py
      - store_artifacts:
          path: src/logs
          destination: logs

  dependency_scan:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Snyk Security Scan with npx
          command: snyk test --file=requirements.txt --package-manager=pip  #here


  verify_withdrawal_mechanism:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Validate consent management
          command: bash src/scripts/verify_withdrawal_mechanism.sh

  third_party_data_handling:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Validate third-party data handling
          command: bash src/scripts/third-party-data-handling.sh

workflows:
  version: 2
  gdpr_pipeline:
    jobs:
      - run_mock_python_app
      - audit_check:
          requires:
            - run_mock_python_app
      - consent_check:
          requires:
            - run_mock_python_app
      - generate_report:
          requires:
            - audit_check
            - consent_check
      - dependency_scan:
          requires:
            - run_mock_python_app
      - verify_withdrawal_mechanism:
          requires:
            - run_mock_python_app
      - third_party_data_handling:
          requires:
            - run_mock_python_app