version: 2.1

jobs:
  install_deps:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout

  audit_check:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Run audit logs check
          command: src/scripts/check-audit-logs.sh
      - store_artifacts:
          path: src/logs
          destination: logs

  consent_check:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Run consent logs check
          command: src/scripts/check-consent-logs.sh
      - store_artifacts:
          path: src/logs/consent.log
          destination: consent-logs

  generate_report:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Generate compliance report
          command: python src/scripts/generate_report.py
      - store_artifacts:
          path: src/logs
          destination: logs

  run_mock_python_app:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Ensure logs directory exists and set permissions
          command: |
            mkdir -p src/logs
            chmod -R 777 src/logs
      - run:
          name: Run mock Python application
          command: python src/app.py 
      - run:
          name: Debug logs directory
          command: ls -l src/logs
      - store_artifacts:
          path: src/logs
          destination: logs

workflows:
  version: 2
  gdpr_pipeline:
    jobs:
      - install_deps
      - run_mock_python_app:
          requires:
            - install_deps
      - audit_check:
          requires:
            - run_mock_python_app
      - consent_check:
          requires:
            - run_mock_python_app
      - generate_report:
          requires:
            - audit_check
            - consent_check
