version: 2.1

jobs:
  install_deps:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout

  run_mock_python_app:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Ensure logs directory exists and set permissions
          command: |
            mkdir -p src/logs
            chmod -R 777 src/logs
      - run:
          name: Run mock Python application
          command: python src/app.py
      - run:
          name: Verify logs directory and files
          command: |
            ls -l src/logs
            cat src/logs/audit.log || echo "audit.log not found"
            cat src/logs/consent.log || echo "consent.log not found"
      - persist_to_workspace:
          root: .
          paths:
            - src/logs

  audit_check:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: List files in workspace to verify log paths
          command: |
            ls -l /workspace/src/logs
            cat /workspace/src/logs/audit.log || echo "audit.log not found"
      - run:
          name: Run audit logs check
          command: /workspace/src/scripts/check-audit-logs.sh
      - store_artifacts:
          path: /workspace/src/logs
          destination: logs

  consent_check:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: List files in workspace to verify log paths
          command: |
            ls -l /workspace/src/logs
            cat /workspace/src/logs/consent.log || echo "consent.log not found"
      - run:
          name: Run consent logs check
          command: /workspace/src/scripts/check-consent-logs.sh
      - store_artifacts:
          path: /workspace/src/logs/consent.log
          destination: consent-logs

  generate_report:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Generate compliance report
          command: python /workspace/src/scripts/generate_report.py
      - store_artifacts:
          path: /workspace/src/logs
          destination: logs

workflows:
  version: 2
  gdpr_pipeline:
    jobs:
      - install_deps
      - run_mock_python_app:
          requires:
            - install_deps
      - audit_check:
          requires:
            - run_mock_python_app
      - consent_check:
          requires:
            - run_mock_python_app
      - generate_report:
          requires:
            - audit_check
            - consent_check
